import type { Locale } from "@/i18n/routing";
import type { LegalContent } from "../components/LegalDocument";

export const CONTACT_EMAIL = "lumo-nodejs-scrapper@protonmail.com";
const UPDATED = "2026-09-18";

/**
 * Privacy Policy. Describes what Aura actually does today (auth, catalog, YouTube playback) and what
 * the platform is designed to do (listening history, social features) — update it when a new kind of
 * data starts being collected. Shown on /privacy and linked from the Google OAuth consent screen.
 */
export const privacy: Record<Locale, LegalContent> = {
  en: {
    title: "Privacy Policy",
    updated: `Last updated: ${UPDATED}`,
    intro: [
      "Aura is a music-social streaming platform: you search for music, play it, build playlists, and see what your friends are listening to. This policy explains what personal data Aura collects, why, and what you can do about it.",
      "Aura is an independent, non-commercial project operated by an individual developer based in Bulgaria (European Union). It is currently in development and available to a limited group of test users.",
    ],
    sections: [
      {
        heading: "Who is responsible",
        body: [
          `The data controller is the individual developer of Aura. You can reach us at ${CONTACT_EMAIL} for anything related to your data.`,
        ],
      },
      {
        heading: "What we collect",
        body: [
          "Account data — when you create an account we store your email address, a display name, a username, and a password hash (never the password itself). If you sign in with Google, we receive from Google your email address, name, and profile picture URL, and we store an identifier for your Google account so you can sign in again. We do not receive or store your Google password.",
          "Session data — a session cookie, plus the IP address and browser user agent of the device that created the session, so you can review and revoke sessions.",
          "Listening data — which tracks, albums and artists you play, like, add to playlists or follow, and when. This is what powers your library, recently played, recommendations and the “currently listening” signal your friends can see.",
          "Social data — friends, friend requests, follows, and the activity generated by these actions (for example “Anna liked Blue”).",
          "Technical data — request logs (path, status, timing, a request id) kept for debugging and abuse prevention. We do not use advertising trackers or third-party analytics.",
        ],
      },
      {
        heading: "Why we use it (legal bases)",
        body: [
          [
            "To provide the service you asked for — account, playback, library, social features (performance of a contract, GDPR art. 6(1)(b)).",
            "To keep the service secure — sessions, abuse and fraud prevention (legitimate interest, art. 6(1)(f)).",
            "To send you emails you asked for — email verification and password reset (contract). We do not send marketing email.",
            "For anything else we will ask for your consent first.",
          ],
        ],
      },
      {
        heading: "Music providers and other third parties",
        body: [
          "Aura does not host music. Metadata (artists, albums, tracks, artwork) comes from TIDAL; artist biographies from Last.fm and Discogs; lyrics from LRCLIB. Playback uses the embedded YouTube player, which means when you play a track your browser talks directly to YouTube/Google and Google's own privacy policy applies to that interaction (https://policies.google.com/privacy).",
          "Requests to these providers are made by our servers with catalog identifiers (for example a track title or an ISRC code). We do not send them your name, email or account identifiers.",
          "Infrastructure: our database is hosted by Supabase in the EU (Frankfurt, AWS eu-central-1); backend services run on Render; the web app is served through Cloudflare; transactional email is sent through Resend. These processors act on our instructions under data processing agreements.",
        ],
      },
      {
        heading: "Google Sign-In",
        body: [
          "If you choose “Continue with Google”, Aura requests only your basic profile (name, email, profile picture). We use it to create or sign in to your Aura account. Aura's use of information received from Google APIs adheres to the Google API Services User Data Policy, including the Limited Use requirements. You can revoke Aura's access at any time from your Google Account permissions page.",
        ],
      },
      {
        heading: "Retention",
        body: [
          "Account and listening data are kept for as long as your account exists. Sessions expire after 30 days of inactivity. Request logs are kept for up to 30 days. When you delete your account, your personal data is removed within 30 days; anonymised aggregate statistics may remain.",
        ],
      },
      {
        heading: "Your rights",
        body: [
          "Under the GDPR you can ask us to access, correct, export or delete your personal data, to restrict or object to processing, and you may withdraw consent at any time. Write to the contact address above and we will respond within one month. You can also lodge a complaint with your local supervisory authority — in Bulgaria, the Commission for Personal Data Protection (cpdp.bg).",
        ],
      },
      {
        heading: "Cookies",
        body: [
          "Aura uses only strictly necessary cookies: the session cookie that keeps you signed in and a preference cookie for your language. There are no advertising or cross-site tracking cookies.",
        ],
      },
      {
        heading: "Children",
        body: ["Aura is not directed at children under 16, and we do not knowingly collect their data."],
      },
      {
        heading: "Changes",
        body: [
          "We will update this page when something changes and move the date at the top. For significant changes we will notify you in the app or by email.",
        ],
      },
    ],
    footer: { privacy: "Privacy Policy", terms: "Terms of Service", signIn: "Sign in" },
  },

  bg: {
    title: "Политика за поверителност",
    updated: `Последна промяна: ${UPDATED}`,
    intro: [
      "Aura е музикално-социална стрийминг платформа: търсиш музика, слушаш, правиш плейлисти и виждаш какво слушат приятелите ти. Тази политика обяснява какви лични данни събира Aura, защо, и какво можеш да направиш по въпроса.",
      "Aura е независим, некомерсиален проект, разработван от физическо лице в България (Европейски съюз). В момента е в разработка и е достъпен за ограничен кръг тестови потребители.",
    ],
    sections: [
      {
        heading: "Кой отговаря",
        body: [
          `Администратор на данните е разработчикът на Aura. За всичко, свързано с данните ти, пиши на ${CONTACT_EMAIL}.`,
        ],
      },
      {
        heading: "Какво събираме",
        body: [
          "Данни за профила — при регистрация пазим имейл, име за показване, потребителско име и хеш на паролата (никога самата парола). Ако влизаш с Google, получаваме от Google имейл, име и адрес на профилната снимка и пазим идентификатор на Google акаунта ти, за да можеш да влизаш отново. Не получаваме и не пазим паролата ти за Google.",
          "Данни за сесията — бисквитка за сесия, както и IP адрес и браузър (user agent) на устройството, което я е създало, за да можеш да преглеждаш и прекратяваш сесии.",
          "Данни за слушането — кои песни, албуми и изпълнители пускаш, харесваш, добавяш в плейлисти или следваш, и кога. Това захранва библиотеката, „Скоро слушани“, препоръките и сигнала „слуша в момента“, който приятелите ти виждат.",
          "Социални данни — приятели, покани за приятелство, последвания и активността от тези действия (напр. „Анна хареса Blue“).",
          "Технически данни — логове на заявките (път, статус, време, идентификатор на заявката) за отстраняване на проблеми и предотвратяване на злоупотреби. Не използваме рекламни тракери или аналитика на трети страни.",
        ],
      },
      {
        heading: "Защо ги използваме (правни основания)",
        body: [
          [
            "За да предоставим услугата, която си поискал — профил, възпроизвеждане, библиотека, социални функции (изпълнение на договор, чл. 6(1)(б) GDPR).",
            "За сигурност — сесии, предотвратяване на злоупотреби (легитимен интерес, чл. 6(1)(е)).",
            "За имейли, които си поискал — потвърждение на имейл и смяна на парола (договор). Не изпращаме маркетингови имейли.",
            "За всичко друго първо ще поискаме съгласието ти.",
          ],
        ],
      },
      {
        heading: "Музикални доставчици и други трети страни",
        body: [
          "Aura не хоства музика. Метаданните (изпълнители, албуми, песни, обложки) идват от TIDAL; биографиите — от Last.fm и Discogs; текстовете — от LRCLIB. Възпроизвеждането използва вградения YouTube плейър — когато пуснеш песен, браузърът ти комуникира директно с YouTube/Google и за това взаимодействие важи политиката за поверителност на Google (https://policies.google.com/privacy).",
          "Заявките към тези доставчици се правят от нашите сървъри с каталожни идентификатори (напр. заглавие на песен или ISRC код). Не им изпращаме името, имейла или идентификаторите на профила ти.",
          "Инфраструктура: базата данни се хоства от Supabase в ЕС (Франкфурт, AWS eu-central-1); backend услугите работят на Render; уеб приложението се сервира през Cloudflare; служебните имейли се изпращат през Resend. Тези обработващи действат по наши инструкции съгласно споразумения за обработка на данни.",
        ],
      },
      {
        heading: "Вход с Google",
        body: [
          "Ако избереш „Продължи с Google“, Aura иска само основния ти профил (име, имейл, профилна снимка) и го използва, за да създаде или отвори профила ти в Aura. Използването на информация от Google API-та от страна на Aura спазва Google API Services User Data Policy, включително изискванията за ограничена употреба (Limited Use). Можеш да оттеглиш достъпа на Aura по всяко време от страницата с разрешения на Google акаунта си.",
        ],
      },
      {
        heading: "Съхранение",
        body: [
          "Данните за профила и слушането се пазят, докато профилът съществува. Сесиите изтичат след 30 дни без активност. Логовете на заявките се пазят до 30 дни. При изтриване на профила личните ти данни се премахват в рамките на 30 дни; анонимизирана обобщена статистика може да остане.",
        ],
      },
      {
        heading: "Твоите права",
        body: [
          "Съгласно GDPR можеш да поискаш достъп, коригиране, експорт или изтриване на личните си данни, ограничаване на обработката или възражение срещу нея, и да оттеглиш съгласието си по всяко време. Пиши на адреса за контакт по-горе — отговаряме в рамките на един месец. Можеш и да подадеш жалба до надзорния орган — в България това е Комисията за защита на личните данни (cpdp.bg).",
        ],
      },
      {
        heading: "Бисквитки",
        body: [
          "Aura използва само строго необходими бисквитки: бисквитката за сесия, която те държи влязъл, и бисквитка за предпочитан език. Няма рекламни или проследяващи бисквитки.",
        ],
      },
      {
        heading: "Деца",
        body: ["Aura не е предназначена за деца под 16 години и не събираме съзнателно техни данни."],
      },
      {
        heading: "Промени",
        body: [
          "Ще обновяваме тази страница при промяна и ще сменяме датата горе. За съществени промени ще те уведомим в приложението или по имейл.",
        ],
      },
    ],
    footer: { privacy: "Политика за поверителност", terms: "Условия за ползване", signIn: "Вход" },
  },
};
